# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  env:
    - CGO_ENABLED=0
  main: ./cmd/odysseus/main.go
  goos:
    - darwin
    - windows
    - linux
  goarch:
    - 386
    - amd64
    - arm
    
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
      arm: arm
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: '{{ .Tag }}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
